kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 40002
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        audit-policy-file: "/auditing/basic_audit_policy.yaml"
        audit-log-path: "/auditing/audit.log"
      extraVolumes:
      - name: "auditing"
        hostPath: "/auditing"
        mountPath: "/auditing"
        readOnly: false
        pathType: "Directory"
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /home/rorym/Development/k8s_audit
    containerPath: /auditing
    propagation: None
